matrix:
  include:
    - python: 2.7
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - scripts/install_dgraph.sh
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - scripts/build.sh
after_success: coveralls
