language: python
python:
  - "3.6"
  - "2.7"
sudo: required
dist: trusty
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - scripts/install_dgraph.sh
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - scripts/build.sh
after_success: coveralls
