language: python
python:
  - "3.7"
  - "2.7"
sudo: required
dist: xenial
before_install:
  - scripts/install_dgraph.sh
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - scripts/build.sh
after_success: coveralls
