name: Setup Python Environment
description: Sets up Python, uv, and trunk for pydgraph development
inputs:
  python-version:
    description: Python version to install
    required: true
  enable-uv-cache:
    description: Enable uv cache
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: ${{ inputs.enable-uv-cache }}
    - name: Install trunk
      uses: trunk-io/trunk-action/setup@v1
