"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Style guide for Protocol Buffer 3.
Use CamelCase (with an initial capital) for message names – for example,
SongServerRequest. Use underscore_separated_names for field names – for
example, song_name.
"""

import builtins
import collections.abc
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LeaseType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LeaseTypeEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LeaseType.ValueType],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NS: _LeaseType.ValueType  # 0
    UID: _LeaseType.ValueType  # 1
    TS: _LeaseType.ValueType  # 2

class LeaseType(_LeaseType, metaclass=_LeaseTypeEnumTypeWrapper): ...

NS: LeaseType.ValueType  # 0
UID: LeaseType.ValueType  # 1
TS: LeaseType.ValueType  # 2
Global___LeaseType: typing_extensions.TypeAlias = LeaseType

@typing.final
class Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _RespFormat:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _RespFormatEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
            Request._RespFormat.ValueType
        ],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        JSON: Request._RespFormat.ValueType  # 0
        RDF: Request._RespFormat.ValueType  # 1

    class RespFormat(_RespFormat, metaclass=_RespFormatEnumTypeWrapper): ...
    JSON: Request.RespFormat.ValueType  # 0
    RDF: Request.RespFormat.ValueType  # 1

    @typing.final
    class VarsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
            "key", b"key", "value", b"value"
        ]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    START_TS_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    VARS_FIELD_NUMBER: builtins.int
    READ_ONLY_FIELD_NUMBER: builtins.int
    BEST_EFFORT_FIELD_NUMBER: builtins.int
    MUTATIONS_FIELD_NUMBER: builtins.int
    COMMIT_NOW_FIELD_NUMBER: builtins.int
    RESP_FORMAT_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    start_ts: builtins.int
    query: builtins.str
    read_only: builtins.bool
    best_effort: builtins.bool
    commit_now: builtins.bool
    resp_format: Global___Request.RespFormat.ValueType
    hash: builtins.str
    @property
    def vars(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Support for GraphQL like variables."""

    @property
    def mutations(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Mutation
    ]: ...
    def __init__(
        self,
        *,
        start_ts: builtins.int = ...,
        query: builtins.str = ...,
        vars: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        read_only: builtins.bool = ...,
        best_effort: builtins.bool = ...,
        mutations: collections.abc.Iterable[Global___Mutation] | None = ...,
        commit_now: builtins.bool = ...,
        resp_format: Global___Request.RespFormat.ValueType = ...,
        hash: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "best_effort",
        b"best_effort",
        "commit_now",
        b"commit_now",
        "hash",
        b"hash",
        "mutations",
        b"mutations",
        "query",
        b"query",
        "read_only",
        b"read_only",
        "resp_format",
        b"resp_format",
        "start_ts",
        b"start_ts",
        "vars",
        b"vars",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Request: typing_extensions.TypeAlias = Request

@typing.final
class Uids(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UIDS_FIELD_NUMBER: builtins.int
    @property
    def uids(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.str
    ]: ...
    def __init__(
        self,
        *,
        uids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["uids", b"uids"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Uids: typing_extensions.TypeAlias = Uids

@typing.final
class ListOfString(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.str
    ]: ...
    def __init__(
        self,
        *,
        value: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["value", b"value"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListOfString: typing_extensions.TypeAlias = ListOfString

@typing.final
class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class UidsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
            "key", b"key", "value", b"value"
        ]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @typing.final
    class HdrsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___ListOfString: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___ListOfString | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal[
            "value", b"value"
        ]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
            "key", b"key", "value", b"value"
        ]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    JSON_FIELD_NUMBER: builtins.int
    TXN_FIELD_NUMBER: builtins.int
    LATENCY_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    UIDS_FIELD_NUMBER: builtins.int
    RDF_FIELD_NUMBER: builtins.int
    HDRS_FIELD_NUMBER: builtins.int
    json: builtins.bytes
    rdf: builtins.bytes
    @property
    def txn(self) -> Global___TxnContext: ...
    @property
    def latency(self) -> Global___Latency: ...
    @property
    def metrics(self) -> Global___Metrics:
        """Metrics contains all metrics related to the query."""

    @property
    def uids(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """uids contains a mapping of blank_node => uid for the node. It only returns uids
        that were created as part of a mutation.
        """

    @property
    def hdrs(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___ListOfString
    ]: ...
    def __init__(
        self,
        *,
        json: builtins.bytes = ...,
        txn: Global___TxnContext | None = ...,
        latency: Global___Latency | None = ...,
        metrics: Global___Metrics | None = ...,
        uids: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        rdf: builtins.bytes = ...,
        hdrs: collections.abc.Mapping[builtins.str, Global___ListOfString] | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "latency", b"latency", "metrics", b"metrics", "txn", b"txn"
    ]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "hdrs",
        b"hdrs",
        "json",
        b"json",
        "latency",
        b"latency",
        "metrics",
        b"metrics",
        "rdf",
        b"rdf",
        "txn",
        b"txn",
        "uids",
        b"uids",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Response: typing_extensions.TypeAlias = Response

@typing.final
class Mutation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SET_JSON_FIELD_NUMBER: builtins.int
    DELETE_JSON_FIELD_NUMBER: builtins.int
    SET_NQUADS_FIELD_NUMBER: builtins.int
    DEL_NQUADS_FIELD_NUMBER: builtins.int
    SET_FIELD_NUMBER: builtins.int
    DEL_FIELD_NUMBER: builtins.int
    COND_FIELD_NUMBER: builtins.int
    COMMIT_NOW_FIELD_NUMBER: builtins.int
    set_json: builtins.bytes
    delete_json: builtins.bytes
    set_nquads: builtins.bytes
    del_nquads: builtins.bytes
    cond: builtins.str
    """This is being used for upserts."""
    commit_now: builtins.bool
    """This field is a duplicate of the one in Request and placed here for convenience."""
    @property
    def set(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___NQuad
    ]: ...
    def __init__(
        self,
        *,
        set_json: builtins.bytes = ...,
        delete_json: builtins.bytes = ...,
        set_nquads: builtins.bytes = ...,
        del_nquads: builtins.bytes = ...,
        set: collections.abc.Iterable[Global___NQuad] | None = ...,
        cond: builtins.str = ...,
        commit_now: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "commit_now",
        b"commit_now",
        "cond",
        b"cond",
        "del",
        b"del",
        "del_nquads",
        b"del_nquads",
        "delete_json",
        b"delete_json",
        "set",
        b"set",
        "set_json",
        b"set_json",
        "set_nquads",
        b"set_nquads",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Mutation: typing_extensions.TypeAlias = Mutation

@typing.final
class Operation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _DropOp:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DropOpEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
            Operation._DropOp.ValueType
        ],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NONE: Operation._DropOp.ValueType  # 0
        ALL: Operation._DropOp.ValueType  # 1
        DATA: Operation._DropOp.ValueType  # 2
        ATTR: Operation._DropOp.ValueType  # 3
        TYPE: Operation._DropOp.ValueType  # 4

    class DropOp(_DropOp, metaclass=_DropOpEnumTypeWrapper): ...
    NONE: Operation.DropOp.ValueType  # 0
    ALL: Operation.DropOp.ValueType  # 1
    DATA: Operation.DropOp.ValueType  # 2
    ATTR: Operation.DropOp.ValueType  # 3
    TYPE: Operation.DropOp.ValueType  # 4

    SCHEMA_FIELD_NUMBER: builtins.int
    DROP_ATTR_FIELD_NUMBER: builtins.int
    DROP_ALL_FIELD_NUMBER: builtins.int
    DROP_OP_FIELD_NUMBER: builtins.int
    DROP_VALUE_FIELD_NUMBER: builtins.int
    RUN_IN_BACKGROUND_FIELD_NUMBER: builtins.int
    schema: builtins.str
    drop_attr: builtins.str
    drop_all: builtins.bool
    drop_op: Global___Operation.DropOp.ValueType
    drop_value: builtins.str
    """If drop_op is ATTR or TYPE, drop_value holds the name of the predicate or
    type to delete.
    """
    run_in_background: builtins.bool
    """run indexes in background."""
    def __init__(
        self,
        *,
        schema: builtins.str = ...,
        drop_attr: builtins.str = ...,
        drop_all: builtins.bool = ...,
        drop_op: Global___Operation.DropOp.ValueType = ...,
        drop_value: builtins.str = ...,
        run_in_background: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "drop_all",
        b"drop_all",
        "drop_attr",
        b"drop_attr",
        "drop_op",
        b"drop_op",
        "drop_value",
        b"drop_value",
        "run_in_background",
        b"run_in_background",
        "schema",
        b"schema",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Operation: typing_extensions.TypeAlias = Operation

@typing.final
class Payload(google.protobuf.message.Message):
    """Worker services."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    Data: builtins.bytes
    def __init__(
        self,
        *,
        Data: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["Data", b"Data"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Payload: typing_extensions.TypeAlias = Payload

@typing.final
class TxnContext(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_TS_FIELD_NUMBER: builtins.int
    COMMIT_TS_FIELD_NUMBER: builtins.int
    ABORTED_FIELD_NUMBER: builtins.int
    KEYS_FIELD_NUMBER: builtins.int
    PREDS_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    start_ts: builtins.int
    commit_ts: builtins.int
    aborted: builtins.bool
    hash: builtins.str
    @property
    def keys(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of keys to be used for conflict detection."""

    @property
    def preds(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of predicates involved in this transaction."""

    def __init__(
        self,
        *,
        start_ts: builtins.int = ...,
        commit_ts: builtins.int = ...,
        aborted: builtins.bool = ...,
        keys: collections.abc.Iterable[builtins.str] | None = ...,
        preds: collections.abc.Iterable[builtins.str] | None = ...,
        hash: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "aborted",
        b"aborted",
        "commit_ts",
        b"commit_ts",
        "hash",
        b"hash",
        "keys",
        b"keys",
        "preds",
        b"preds",
        "start_ts",
        b"start_ts",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TxnContext: typing_extensions.TypeAlias = TxnContext

@typing.final
class Check(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Check: typing_extensions.TypeAlias = Check

@typing.final
class Version(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    tag: builtins.str
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["tag", b"tag"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Version: typing_extensions.TypeAlias = Version

@typing.final
class Latency(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARSING_NS_FIELD_NUMBER: builtins.int
    PROCESSING_NS_FIELD_NUMBER: builtins.int
    ENCODING_NS_FIELD_NUMBER: builtins.int
    ASSIGN_TIMESTAMP_NS_FIELD_NUMBER: builtins.int
    TOTAL_NS_FIELD_NUMBER: builtins.int
    parsing_ns: builtins.int
    processing_ns: builtins.int
    encoding_ns: builtins.int
    assign_timestamp_ns: builtins.int
    total_ns: builtins.int
    def __init__(
        self,
        *,
        parsing_ns: builtins.int = ...,
        processing_ns: builtins.int = ...,
        encoding_ns: builtins.int = ...,
        assign_timestamp_ns: builtins.int = ...,
        total_ns: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "assign_timestamp_ns",
        b"assign_timestamp_ns",
        "encoding_ns",
        b"encoding_ns",
        "parsing_ns",
        b"parsing_ns",
        "processing_ns",
        b"processing_ns",
        "total_ns",
        b"total_ns",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Latency: typing_extensions.TypeAlias = Latency

@typing.final
class Metrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class NumUidsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
            "key", b"key", "value", b"value"
        ]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NUM_UIDS_FIELD_NUMBER: builtins.int
    @property
    def num_uids(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.int]:
        """num_uids is the map of number of uids processed by each attribute."""

    def __init__(
        self,
        *,
        num_uids: collections.abc.Mapping[builtins.str, builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "num_uids", b"num_uids"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Metrics: typing_extensions.TypeAlias = Metrics

@typing.final
class NQuad(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBJECT_FIELD_NUMBER: builtins.int
    PREDICATE_FIELD_NUMBER: builtins.int
    OBJECT_ID_FIELD_NUMBER: builtins.int
    OBJECT_VALUE_FIELD_NUMBER: builtins.int
    LANG_FIELD_NUMBER: builtins.int
    FACETS_FIELD_NUMBER: builtins.int
    NAMESPACE_FIELD_NUMBER: builtins.int
    subject: builtins.str
    predicate: builtins.str
    object_id: builtins.str
    lang: builtins.str
    namespace: builtins.int
    @property
    def object_value(self) -> Global___Value: ...
    @property
    def facets(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Facet
    ]: ...
    def __init__(
        self,
        *,
        subject: builtins.str = ...,
        predicate: builtins.str = ...,
        object_id: builtins.str = ...,
        object_value: Global___Value | None = ...,
        lang: builtins.str = ...,
        facets: collections.abc.Iterable[Global___Facet] | None = ...,
        namespace: builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "object_value", b"object_value"
    ]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "facets",
        b"facets",
        "lang",
        b"lang",
        "namespace",
        b"namespace",
        "object_id",
        b"object_id",
        "object_value",
        b"object_value",
        "predicate",
        b"predicate",
        "subject",
        b"subject",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NQuad: typing_extensions.TypeAlias = NQuad

@typing.final
class Value(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFAULT_VAL_FIELD_NUMBER: builtins.int
    BYTES_VAL_FIELD_NUMBER: builtins.int
    INT_VAL_FIELD_NUMBER: builtins.int
    BOOL_VAL_FIELD_NUMBER: builtins.int
    STR_VAL_FIELD_NUMBER: builtins.int
    DOUBLE_VAL_FIELD_NUMBER: builtins.int
    GEO_VAL_FIELD_NUMBER: builtins.int
    DATE_VAL_FIELD_NUMBER: builtins.int
    DATETIME_VAL_FIELD_NUMBER: builtins.int
    PASSWORD_VAL_FIELD_NUMBER: builtins.int
    UID_VAL_FIELD_NUMBER: builtins.int
    BIGFLOAT_VAL_FIELD_NUMBER: builtins.int
    VFLOAT32_VAL_FIELD_NUMBER: builtins.int
    default_val: builtins.str
    bytes_val: builtins.bytes
    int_val: builtins.int
    bool_val: builtins.bool
    str_val: builtins.str
    double_val: builtins.float
    geo_val: builtins.bytes
    """Geo data in WKB format"""
    date_val: builtins.bytes
    datetime_val: builtins.bytes
    password_val: builtins.str
    uid_val: builtins.int
    bigfloat_val: builtins.bytes
    vfloat32_val: builtins.bytes
    def __init__(
        self,
        *,
        default_val: builtins.str = ...,
        bytes_val: builtins.bytes = ...,
        int_val: builtins.int = ...,
        bool_val: builtins.bool = ...,
        str_val: builtins.str = ...,
        double_val: builtins.float = ...,
        geo_val: builtins.bytes = ...,
        date_val: builtins.bytes = ...,
        datetime_val: builtins.bytes = ...,
        password_val: builtins.str = ...,
        uid_val: builtins.int = ...,
        bigfloat_val: builtins.bytes = ...,
        vfloat32_val: builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "bigfloat_val",
        b"bigfloat_val",
        "bool_val",
        b"bool_val",
        "bytes_val",
        b"bytes_val",
        "date_val",
        b"date_val",
        "datetime_val",
        b"datetime_val",
        "default_val",
        b"default_val",
        "double_val",
        b"double_val",
        "geo_val",
        b"geo_val",
        "int_val",
        b"int_val",
        "password_val",
        b"password_val",
        "str_val",
        b"str_val",
        "uid_val",
        b"uid_val",
        "val",
        b"val",
        "vfloat32_val",
        b"vfloat32_val",
    ]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "bigfloat_val",
        b"bigfloat_val",
        "bool_val",
        b"bool_val",
        "bytes_val",
        b"bytes_val",
        "date_val",
        b"date_val",
        "datetime_val",
        b"datetime_val",
        "default_val",
        b"default_val",
        "double_val",
        b"double_val",
        "geo_val",
        b"geo_val",
        "int_val",
        b"int_val",
        "password_val",
        b"password_val",
        "str_val",
        b"str_val",
        "uid_val",
        b"uid_val",
        "val",
        b"val",
        "vfloat32_val",
        b"vfloat32_val",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_val: typing_extensions.TypeAlias = typing.Literal[
        "default_val",
        "bytes_val",
        "int_val",
        "bool_val",
        "str_val",
        "double_val",
        "geo_val",
        "date_val",
        "datetime_val",
        "password_val",
        "uid_val",
        "bigfloat_val",
        "vfloat32_val",
    ]
    _WhichOneofArgType_val: typing_extensions.TypeAlias = typing.Literal["val", b"val"]
    def WhichOneof(
        self, oneof_group: _WhichOneofArgType_val
    ) -> _WhichOneofReturnType_val | None: ...

Global___Value: typing_extensions.TypeAlias = Value

@typing.final
class Facet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ValType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ValTypeEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
            Facet._ValType.ValueType
        ],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STRING: Facet._ValType.ValueType  # 0
        INT: Facet._ValType.ValueType  # 1
        FLOAT: Facet._ValType.ValueType  # 2
        BOOL: Facet._ValType.ValueType  # 3
        DATETIME: Facet._ValType.ValueType  # 4

    class ValType(_ValType, metaclass=_ValTypeEnumTypeWrapper): ...
    STRING: Facet.ValType.ValueType  # 0
    INT: Facet.ValType.ValueType  # 1
    FLOAT: Facet.ValType.ValueType  # 2
    BOOL: Facet.ValType.ValueType  # 3
    DATETIME: Facet.ValType.ValueType  # 4

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    VAL_TYPE_FIELD_NUMBER: builtins.int
    TOKENS_FIELD_NUMBER: builtins.int
    ALIAS_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.bytes
    val_type: Global___Facet.ValType.ValueType
    alias: builtins.str
    """not stored, only used for query."""
    @property
    def tokens(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """tokens of value."""

    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.bytes = ...,
        val_type: Global___Facet.ValType.ValueType = ...,
        tokens: collections.abc.Iterable[builtins.str] | None = ...,
        alias: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "alias",
        b"alias",
        "key",
        b"key",
        "tokens",
        b"tokens",
        "val_type",
        b"val_type",
        "value",
        b"value",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Facet: typing_extensions.TypeAlias = Facet

@typing.final
class LoginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    NAMESPACE_FIELD_NUMBER: builtins.int
    userid: builtins.str
    password: builtins.str
    refresh_token: builtins.str
    namespace: builtins.int
    def __init__(
        self,
        *,
        userid: builtins.str = ...,
        password: builtins.str = ...,
        refresh_token: builtins.str = ...,
        namespace: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "namespace",
        b"namespace",
        "password",
        b"password",
        "refresh_token",
        b"refresh_token",
        "userid",
        b"userid",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoginRequest: typing_extensions.TypeAlias = LoginRequest

@typing.final
class Jwt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_JWT_FIELD_NUMBER: builtins.int
    REFRESH_JWT_FIELD_NUMBER: builtins.int
    access_jwt: builtins.str
    refresh_jwt: builtins.str
    def __init__(
        self,
        *,
        access_jwt: builtins.str = ...,
        refresh_jwt: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "access_jwt", b"access_jwt", "refresh_jwt", b"refresh_jwt"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Jwt: typing_extensions.TypeAlias = Jwt

@typing.final
class RunDQLRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class VarsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
            "key", b"key", "value", b"value"
        ]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    DQL_QUERY_FIELD_NUMBER: builtins.int
    VARS_FIELD_NUMBER: builtins.int
    READ_ONLY_FIELD_NUMBER: builtins.int
    BEST_EFFORT_FIELD_NUMBER: builtins.int
    RESP_FORMAT_FIELD_NUMBER: builtins.int
    dql_query: builtins.str
    read_only: builtins.bool
    best_effort: builtins.bool
    resp_format: Global___Request.RespFormat.ValueType
    @property
    def vars(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        dql_query: builtins.str = ...,
        vars: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        read_only: builtins.bool = ...,
        best_effort: builtins.bool = ...,
        resp_format: Global___Request.RespFormat.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "best_effort",
        b"best_effort",
        "dql_query",
        b"dql_query",
        "read_only",
        b"read_only",
        "resp_format",
        b"resp_format",
        "vars",
        b"vars",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RunDQLRequest: typing_extensions.TypeAlias = RunDQLRequest

@typing.final
class AllocateIDsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOW_MANY_FIELD_NUMBER: builtins.int
    LEASE_TYPE_FIELD_NUMBER: builtins.int
    how_many: builtins.int
    lease_type: Global___LeaseType.ValueType
    def __init__(
        self,
        *,
        how_many: builtins.int = ...,
        lease_type: Global___LeaseType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "how_many", b"how_many", "lease_type", b"lease_type"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AllocateIDsRequest: typing_extensions.TypeAlias = AllocateIDsRequest

@typing.final
class AllocateIDsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    start: builtins.int
    end: builtins.int
    """inclusive"""
    def __init__(
        self,
        *,
        start: builtins.int = ...,
        end: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "end", b"end", "start", b"start"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AllocateIDsResponse: typing_extensions.TypeAlias = AllocateIDsResponse

@typing.final
class CreateNamespaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CreateNamespaceRequest: typing_extensions.TypeAlias = CreateNamespaceRequest

@typing.final
class CreateNamespaceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    namespace: builtins.int
    def __init__(
        self,
        *,
        namespace: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "namespace", b"namespace"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateNamespaceResponse: typing_extensions.TypeAlias = CreateNamespaceResponse

@typing.final
class DropNamespaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    namespace: builtins.int
    def __init__(
        self,
        *,
        namespace: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "namespace", b"namespace"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DropNamespaceRequest: typing_extensions.TypeAlias = DropNamespaceRequest

@typing.final
class DropNamespaceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DropNamespaceResponse: typing_extensions.TypeAlias = DropNamespaceResponse

@typing.final
class ListNamespacesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ListNamespacesRequest: typing_extensions.TypeAlias = ListNamespacesRequest

@typing.final
class ListNamespacesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class NamespacesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> Global___Namespace: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: Global___Namespace | None = ...,
        ) -> None: ...
        _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal[
            "value", b"value"
        ]
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
            "key", b"key", "value", b"value"
        ]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NAMESPACES_FIELD_NUMBER: builtins.int
    @property
    def namespaces(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.int, Global___Namespace
    ]: ...
    def __init__(
        self,
        *,
        namespaces: (
            collections.abc.Mapping[builtins.int, Global___Namespace] | None
        ) = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "namespaces", b"namespaces"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListNamespacesResponse: typing_extensions.TypeAlias = ListNamespacesResponse

@typing.final
class Namespace(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["id", b"id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Namespace: typing_extensions.TypeAlias = Namespace

@typing.final
class UpdateExtSnapshotStreamingStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    FINISH_FIELD_NUMBER: builtins.int
    DROP_DATA_FIELD_NUMBER: builtins.int
    start: builtins.bool
    finish: builtins.bool
    drop_data: builtins.bool
    def __init__(
        self,
        *,
        start: builtins.bool = ...,
        finish: builtins.bool = ...,
        drop_data: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "drop_data", b"drop_data", "finish", b"finish", "start", b"start"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateExtSnapshotStreamingStateRequest: typing_extensions.TypeAlias = (
    UpdateExtSnapshotStreamingStateRequest
)

@typing.final
class UpdateExtSnapshotStreamingStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GROUPS_FIELD_NUMBER: builtins.int
    @property
    def groups(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.int
    ]: ...
    def __init__(
        self,
        *,
        groups: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "groups", b"groups"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateExtSnapshotStreamingStateResponse: typing_extensions.TypeAlias = (
    UpdateExtSnapshotStreamingStateResponse
)

@typing.final
class StreamExtSnapshotRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GROUP_ID_FIELD_NUMBER: builtins.int
    FORWARD_FIELD_NUMBER: builtins.int
    PKT_FIELD_NUMBER: builtins.int
    group_id: builtins.int
    forward: builtins.bool
    @property
    def pkt(self) -> Global___StreamPacket: ...
    def __init__(
        self,
        *,
        group_id: builtins.int = ...,
        forward: builtins.bool = ...,
        pkt: Global___StreamPacket | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["pkt", b"pkt"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "forward", b"forward", "group_id", b"group_id", "pkt", b"pkt"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamExtSnapshotRequest: typing_extensions.TypeAlias = (
    StreamExtSnapshotRequest
)

@typing.final
class StreamExtSnapshotResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StreamExtSnapshotResponse: typing_extensions.TypeAlias = (
    StreamExtSnapshotResponse
)

@typing.final
class StreamPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    DONE_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    done: builtins.bool
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        done: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal[
        "data", b"data", "done", b"done"
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamPacket: typing_extensions.TypeAlias = StreamPacket
