"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Style guide for Protocol Buffer 3.
Use CamelCase (with an initial capital) for message names – for example,
SongServerRequest. Use underscore_separated_names for field names – for
example, song_name.
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import api_pb2 as _api_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DgraphStub:
    """Graph response."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DgraphAsyncStub: ...
    Login: _grpc.UnaryUnaryMultiCallable[_api_pb2.LoginRequest, _api_pb2.Response]
    Query: _grpc.UnaryUnaryMultiCallable[_api_pb2.Request, _api_pb2.Response]
    Alter: _grpc.UnaryUnaryMultiCallable[_api_pb2.Operation, _api_pb2.Payload]
    CommitOrAbort: _grpc.UnaryUnaryMultiCallable[_api_pb2.TxnContext, _api_pb2.TxnContext]
    CheckVersion: _grpc.UnaryUnaryMultiCallable[_api_pb2.Check, _api_pb2.Version]
    RunDQL: _grpc.UnaryUnaryMultiCallable[_api_pb2.RunDQLRequest, _api_pb2.Response]
    AllocateIDs: _grpc.UnaryUnaryMultiCallable[_api_pb2.AllocateIDsRequest, _api_pb2.AllocateIDsResponse]
    UpdateExtSnapshotStreamingState: _grpc.UnaryUnaryMultiCallable[_api_pb2.UpdateExtSnapshotStreamingStateRequest, _api_pb2.UpdateExtSnapshotStreamingStateResponse]
    StreamExtSnapshot: _grpc.StreamUnaryMultiCallable[_api_pb2.StreamExtSnapshotRequest, _api_pb2.StreamExtSnapshotResponse]
    CreateNamespace: _grpc.UnaryUnaryMultiCallable[_api_pb2.CreateNamespaceRequest, _api_pb2.CreateNamespaceResponse]
    DropNamespace: _grpc.UnaryUnaryMultiCallable[_api_pb2.DropNamespaceRequest, _api_pb2.DropNamespaceResponse]
    ListNamespaces: _grpc.UnaryUnaryMultiCallable[_api_pb2.ListNamespacesRequest, _api_pb2.ListNamespacesResponse]

@_typing.type_check_only
class DgraphAsyncStub(DgraphStub):
    """Graph response."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Login: _aio.UnaryUnaryMultiCallable[_api_pb2.LoginRequest, _api_pb2.Response]  # type: ignore[assignment]
    Query: _aio.UnaryUnaryMultiCallable[_api_pb2.Request, _api_pb2.Response]  # type: ignore[assignment]
    Alter: _aio.UnaryUnaryMultiCallable[_api_pb2.Operation, _api_pb2.Payload]  # type: ignore[assignment]
    CommitOrAbort: _aio.UnaryUnaryMultiCallable[_api_pb2.TxnContext, _api_pb2.TxnContext]  # type: ignore[assignment]
    CheckVersion: _aio.UnaryUnaryMultiCallable[_api_pb2.Check, _api_pb2.Version]  # type: ignore[assignment]
    RunDQL: _aio.UnaryUnaryMultiCallable[_api_pb2.RunDQLRequest, _api_pb2.Response]  # type: ignore[assignment]
    AllocateIDs: _aio.UnaryUnaryMultiCallable[_api_pb2.AllocateIDsRequest, _api_pb2.AllocateIDsResponse]  # type: ignore[assignment]
    UpdateExtSnapshotStreamingState: _aio.UnaryUnaryMultiCallable[_api_pb2.UpdateExtSnapshotStreamingStateRequest, _api_pb2.UpdateExtSnapshotStreamingStateResponse]  # type: ignore[assignment]
    StreamExtSnapshot: _aio.StreamUnaryMultiCallable[_api_pb2.StreamExtSnapshotRequest, _api_pb2.StreamExtSnapshotResponse]  # type: ignore[assignment]
    CreateNamespace: _aio.UnaryUnaryMultiCallable[_api_pb2.CreateNamespaceRequest, _api_pb2.CreateNamespaceResponse]  # type: ignore[assignment]
    DropNamespace: _aio.UnaryUnaryMultiCallable[_api_pb2.DropNamespaceRequest, _api_pb2.DropNamespaceResponse]  # type: ignore[assignment]
    ListNamespaces: _aio.UnaryUnaryMultiCallable[_api_pb2.ListNamespacesRequest, _api_pb2.ListNamespacesResponse]  # type: ignore[assignment]

class DgraphServicer(metaclass=_abc_1.ABCMeta):
    """Graph response."""

    @_abc_1.abstractmethod
    def Login(
        self,
        request: _api_pb2.LoginRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.Response, _abc.Awaitable[_api_pb2.Response]]: ...

    @_abc_1.abstractmethod
    def Query(
        self,
        request: _api_pb2.Request,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.Response, _abc.Awaitable[_api_pb2.Response]]: ...

    @_abc_1.abstractmethod
    def Alter(
        self,
        request: _api_pb2.Operation,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.Payload, _abc.Awaitable[_api_pb2.Payload]]: ...

    @_abc_1.abstractmethod
    def CommitOrAbort(
        self,
        request: _api_pb2.TxnContext,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.TxnContext, _abc.Awaitable[_api_pb2.TxnContext]]: ...

    @_abc_1.abstractmethod
    def CheckVersion(
        self,
        request: _api_pb2.Check,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.Version, _abc.Awaitable[_api_pb2.Version]]: ...

    @_abc_1.abstractmethod
    def RunDQL(
        self,
        request: _api_pb2.RunDQLRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.Response, _abc.Awaitable[_api_pb2.Response]]: ...

    @_abc_1.abstractmethod
    def AllocateIDs(
        self,
        request: _api_pb2.AllocateIDsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.AllocateIDsResponse, _abc.Awaitable[_api_pb2.AllocateIDsResponse]]: ...

    @_abc_1.abstractmethod
    def UpdateExtSnapshotStreamingState(
        self,
        request: _api_pb2.UpdateExtSnapshotStreamingStateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.UpdateExtSnapshotStreamingStateResponse, _abc.Awaitable[_api_pb2.UpdateExtSnapshotStreamingStateResponse]]: ...

    @_abc_1.abstractmethod
    def StreamExtSnapshot(
        self,
        request_iterator: _MaybeAsyncIterator[_api_pb2.StreamExtSnapshotRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.StreamExtSnapshotResponse, _abc.Awaitable[_api_pb2.StreamExtSnapshotResponse]]: ...

    @_abc_1.abstractmethod
    def CreateNamespace(
        self,
        request: _api_pb2.CreateNamespaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.CreateNamespaceResponse, _abc.Awaitable[_api_pb2.CreateNamespaceResponse]]: ...

    @_abc_1.abstractmethod
    def DropNamespace(
        self,
        request: _api_pb2.DropNamespaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.DropNamespaceResponse, _abc.Awaitable[_api_pb2.DropNamespaceResponse]]: ...

    @_abc_1.abstractmethod
    def ListNamespaces(
        self,
        request: _api_pb2.ListNamespacesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.ListNamespacesResponse, _abc.Awaitable[_api_pb2.ListNamespacesResponse]]: ...

def add_DgraphServicer_to_server(servicer: DgraphServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
