"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Style guide for Protocol Buffer 3.
Use CamelCase (with an initial capital) for message names – for example,
SongServerRequest. Use underscore_separated_names for field names – for
example, song_name.
"""

import abc
from . import api_pb2
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DgraphStub:
    """Graph response."""

    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> DgraphStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> DgraphAsyncStub: ...
    Login: grpc.UnaryUnaryMultiCallable[api_pb2.LoginRequest, api_pb2.Response]
    Query: grpc.UnaryUnaryMultiCallable[api_pb2.Request, api_pb2.Response]
    Alter: grpc.UnaryUnaryMultiCallable[api_pb2.Operation, api_pb2.Payload]
    CommitOrAbort: grpc.UnaryUnaryMultiCallable[api_pb2.TxnContext, api_pb2.TxnContext]
    CheckVersion: grpc.UnaryUnaryMultiCallable[api_pb2.Check, api_pb2.Version]
    RunDQL: grpc.UnaryUnaryMultiCallable[api_pb2.RunDQLRequest, api_pb2.Response]
    AllocateIDs: grpc.UnaryUnaryMultiCallable[api_pb2.AllocateIDsRequest, api_pb2.AllocateIDsResponse]
    UpdateExtSnapshotStreamingState: grpc.UnaryUnaryMultiCallable[api_pb2.UpdateExtSnapshotStreamingStateRequest, api_pb2.UpdateExtSnapshotStreamingStateResponse]
    StreamExtSnapshot: grpc.StreamUnaryMultiCallable[api_pb2.StreamExtSnapshotRequest, api_pb2.StreamExtSnapshotResponse]
    CreateNamespace: grpc.UnaryUnaryMultiCallable[api_pb2.CreateNamespaceRequest, api_pb2.CreateNamespaceResponse]
    DropNamespace: grpc.UnaryUnaryMultiCallable[api_pb2.DropNamespaceRequest, api_pb2.DropNamespaceResponse]
    ListNamespaces: grpc.UnaryUnaryMultiCallable[api_pb2.ListNamespacesRequest, api_pb2.ListNamespacesResponse]

@typing.type_check_only
class DgraphAsyncStub(DgraphStub):
    """Graph response."""

    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    Login: grpc.aio.UnaryUnaryMultiCallable[api_pb2.LoginRequest, api_pb2.Response]  # type: ignore[assignment]
    Query: grpc.aio.UnaryUnaryMultiCallable[api_pb2.Request, api_pb2.Response]  # type: ignore[assignment]
    Alter: grpc.aio.UnaryUnaryMultiCallable[api_pb2.Operation, api_pb2.Payload]  # type: ignore[assignment]
    CommitOrAbort: grpc.aio.UnaryUnaryMultiCallable[api_pb2.TxnContext, api_pb2.TxnContext]  # type: ignore[assignment]
    CheckVersion: grpc.aio.UnaryUnaryMultiCallable[api_pb2.Check, api_pb2.Version]  # type: ignore[assignment]
    RunDQL: grpc.aio.UnaryUnaryMultiCallable[api_pb2.RunDQLRequest, api_pb2.Response]  # type: ignore[assignment]
    AllocateIDs: grpc.aio.UnaryUnaryMultiCallable[api_pb2.AllocateIDsRequest, api_pb2.AllocateIDsResponse]  # type: ignore[assignment]
    UpdateExtSnapshotStreamingState: grpc.aio.UnaryUnaryMultiCallable[api_pb2.UpdateExtSnapshotStreamingStateRequest, api_pb2.UpdateExtSnapshotStreamingStateResponse]  # type: ignore[assignment]
    StreamExtSnapshot: grpc.aio.StreamUnaryMultiCallable[api_pb2.StreamExtSnapshotRequest, api_pb2.StreamExtSnapshotResponse]  # type: ignore[assignment]
    CreateNamespace: grpc.aio.UnaryUnaryMultiCallable[api_pb2.CreateNamespaceRequest, api_pb2.CreateNamespaceResponse]  # type: ignore[assignment]
    DropNamespace: grpc.aio.UnaryUnaryMultiCallable[api_pb2.DropNamespaceRequest, api_pb2.DropNamespaceResponse]  # type: ignore[assignment]
    ListNamespaces: grpc.aio.UnaryUnaryMultiCallable[api_pb2.ListNamespacesRequest, api_pb2.ListNamespacesResponse]  # type: ignore[assignment]

class DgraphServicer(metaclass=abc.ABCMeta):
    """Graph response."""

    @abc.abstractmethod
    def Login(
        self,
        request: api_pb2.LoginRequest,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.Response, collections.abc.Awaitable[api_pb2.Response]]: ...

    @abc.abstractmethod
    def Query(
        self,
        request: api_pb2.Request,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.Response, collections.abc.Awaitable[api_pb2.Response]]: ...

    @abc.abstractmethod
    def Alter(
        self,
        request: api_pb2.Operation,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.Payload, collections.abc.Awaitable[api_pb2.Payload]]: ...

    @abc.abstractmethod
    def CommitOrAbort(
        self,
        request: api_pb2.TxnContext,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.TxnContext, collections.abc.Awaitable[api_pb2.TxnContext]]: ...

    @abc.abstractmethod
    def CheckVersion(
        self,
        request: api_pb2.Check,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.Version, collections.abc.Awaitable[api_pb2.Version]]: ...

    @abc.abstractmethod
    def RunDQL(
        self,
        request: api_pb2.RunDQLRequest,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.Response, collections.abc.Awaitable[api_pb2.Response]]: ...

    @abc.abstractmethod
    def AllocateIDs(
        self,
        request: api_pb2.AllocateIDsRequest,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.AllocateIDsResponse, collections.abc.Awaitable[api_pb2.AllocateIDsResponse]]: ...

    @abc.abstractmethod
    def UpdateExtSnapshotStreamingState(
        self,
        request: api_pb2.UpdateExtSnapshotStreamingStateRequest,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.UpdateExtSnapshotStreamingStateResponse, collections.abc.Awaitable[api_pb2.UpdateExtSnapshotStreamingStateResponse]]: ...

    @abc.abstractmethod
    def StreamExtSnapshot(
        self,
        request_iterator: _MaybeAsyncIterator[api_pb2.StreamExtSnapshotRequest],
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.StreamExtSnapshotResponse, collections.abc.Awaitable[api_pb2.StreamExtSnapshotResponse]]: ...

    @abc.abstractmethod
    def CreateNamespace(
        self,
        request: api_pb2.CreateNamespaceRequest,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.CreateNamespaceResponse, collections.abc.Awaitable[api_pb2.CreateNamespaceResponse]]: ...

    @abc.abstractmethod
    def DropNamespace(
        self,
        request: api_pb2.DropNamespaceRequest,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.DropNamespaceResponse, collections.abc.Awaitable[api_pb2.DropNamespaceResponse]]: ...

    @abc.abstractmethod
    def ListNamespaces(
        self,
        request: api_pb2.ListNamespacesRequest,
        context: _ServicerContext,
    ) -> typing.Union[api_pb2.ListNamespacesResponse, collections.abc.Awaitable[api_pb2.ListNamespacesResponse]]: ...

def add_DgraphServicer_to_server(servicer: DgraphServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
