"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Style guide for Protocol Buffer 3.
Use CamelCase (with an initial capital) for message names – for example,
SongServerRequest. Use underscore_separated_names for field names – for
example, song_name.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _LeaseType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LeaseTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LeaseType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NS: _LeaseType.ValueType  # 0
    UID: _LeaseType.ValueType  # 1
    TS: _LeaseType.ValueType  # 2

class LeaseType(_LeaseType, metaclass=_LeaseTypeEnumTypeWrapper): ...

NS: LeaseType.ValueType  # 0
UID: LeaseType.ValueType  # 1
TS: LeaseType.ValueType  # 2
Global___LeaseType: _TypeAlias = LeaseType  # noqa: Y015

@_typing.final
class Request(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _RespFormat:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RespFormatEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Request._RespFormat.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        JSON: Request._RespFormat.ValueType  # 0
        RDF: Request._RespFormat.ValueType  # 1

    class RespFormat(_RespFormat, metaclass=_RespFormatEnumTypeWrapper): ...
    JSON: Request.RespFormat.ValueType  # 0
    RDF: Request.RespFormat.ValueType  # 1

    @_typing.final
    class VarsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    START_TS_FIELD_NUMBER: _builtins.int
    QUERY_FIELD_NUMBER: _builtins.int
    VARS_FIELD_NUMBER: _builtins.int
    READ_ONLY_FIELD_NUMBER: _builtins.int
    BEST_EFFORT_FIELD_NUMBER: _builtins.int
    MUTATIONS_FIELD_NUMBER: _builtins.int
    COMMIT_NOW_FIELD_NUMBER: _builtins.int
    RESP_FORMAT_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    start_ts: _builtins.int
    query: _builtins.str
    read_only: _builtins.bool
    best_effort: _builtins.bool
    commit_now: _builtins.bool
    resp_format: Global___Request.RespFormat.ValueType
    hash: _builtins.str
    @_builtins.property
    def vars(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Support for GraphQL like variables."""

    @_builtins.property
    def mutations(self) -> _containers.RepeatedCompositeFieldContainer[Global___Mutation]: ...
    def __init__(
        self,
        *,
        start_ts: _builtins.int = ...,
        query: _builtins.str = ...,
        vars: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        read_only: _builtins.bool = ...,
        best_effort: _builtins.bool = ...,
        mutations: _abc.Iterable[Global___Mutation] | None = ...,
        commit_now: _builtins.bool = ...,
        resp_format: Global___Request.RespFormat.ValueType = ...,
        hash: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["best_effort", b"best_effort", "commit_now", b"commit_now", "hash", b"hash", "mutations", b"mutations", "query", b"query", "read_only", b"read_only", "resp_format", b"resp_format", "start_ts", b"start_ts", "vars", b"vars"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Request: _TypeAlias = Request  # noqa: Y015

@_typing.final
class Uids(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UIDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def uids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        uids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["uids", b"uids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Uids: _TypeAlias = Uids  # noqa: Y015

@_typing.final
class ListOfString(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def value(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        value: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListOfString: _TypeAlias = ListOfString  # noqa: Y015

@_typing.final
class Response(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class UidsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class HdrsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___ListOfString: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___ListOfString | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    JSON_FIELD_NUMBER: _builtins.int
    TXN_FIELD_NUMBER: _builtins.int
    LATENCY_FIELD_NUMBER: _builtins.int
    METRICS_FIELD_NUMBER: _builtins.int
    UIDS_FIELD_NUMBER: _builtins.int
    RDF_FIELD_NUMBER: _builtins.int
    HDRS_FIELD_NUMBER: _builtins.int
    json: _builtins.bytes
    rdf: _builtins.bytes
    @_builtins.property
    def txn(self) -> Global___TxnContext: ...
    @_builtins.property
    def latency(self) -> Global___Latency: ...
    @_builtins.property
    def metrics(self) -> Global___Metrics:
        """Metrics contains all metrics related to the query."""

    @_builtins.property
    def uids(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """uids contains a mapping of blank_node => uid for the node. It only returns uids
        that were created as part of a mutation.
        """

    @_builtins.property
    def hdrs(self) -> _containers.MessageMap[_builtins.str, Global___ListOfString]: ...
    def __init__(
        self,
        *,
        json: _builtins.bytes = ...,
        txn: Global___TxnContext | None = ...,
        latency: Global___Latency | None = ...,
        metrics: Global___Metrics | None = ...,
        uids: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        rdf: _builtins.bytes = ...,
        hdrs: _abc.Mapping[_builtins.str, Global___ListOfString] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["latency", b"latency", "metrics", b"metrics", "txn", b"txn"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hdrs", b"hdrs", "json", b"json", "latency", b"latency", "metrics", b"metrics", "rdf", b"rdf", "txn", b"txn", "uids", b"uids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Response: _TypeAlias = Response  # noqa: Y015

@_typing.final
class Mutation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SET_JSON_FIELD_NUMBER: _builtins.int
    DELETE_JSON_FIELD_NUMBER: _builtins.int
    SET_NQUADS_FIELD_NUMBER: _builtins.int
    DEL_NQUADS_FIELD_NUMBER: _builtins.int
    SET_FIELD_NUMBER: _builtins.int
    DEL_FIELD_NUMBER: _builtins.int
    COND_FIELD_NUMBER: _builtins.int
    COMMIT_NOW_FIELD_NUMBER: _builtins.int
    set_json: _builtins.bytes
    delete_json: _builtins.bytes
    set_nquads: _builtins.bytes
    del_nquads: _builtins.bytes
    cond: _builtins.str
    """This is being used for upserts."""
    commit_now: _builtins.bool
    """This field is a duplicate of the one in Request and placed here for convenience."""
    @_builtins.property
    def set(self) -> _containers.RepeatedCompositeFieldContainer[Global___NQuad]: ...
    def __init__(
        self,
        *,
        set_json: _builtins.bytes = ...,
        delete_json: _builtins.bytes = ...,
        set_nquads: _builtins.bytes = ...,
        del_nquads: _builtins.bytes = ...,
        set: _abc.Iterable[Global___NQuad] | None = ...,
        cond: _builtins.str = ...,
        commit_now: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit_now", b"commit_now", "cond", b"cond", "del", b"del", "del_nquads", b"del_nquads", "delete_json", b"delete_json", "set", b"set", "set_json", b"set_json", "set_nquads", b"set_nquads"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Mutation: _TypeAlias = Mutation  # noqa: Y015

@_typing.final
class Operation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _DropOp:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DropOpEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Operation._DropOp.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NONE: Operation._DropOp.ValueType  # 0
        ALL: Operation._DropOp.ValueType  # 1
        DATA: Operation._DropOp.ValueType  # 2
        ATTR: Operation._DropOp.ValueType  # 3
        TYPE: Operation._DropOp.ValueType  # 4

    class DropOp(_DropOp, metaclass=_DropOpEnumTypeWrapper): ...
    NONE: Operation.DropOp.ValueType  # 0
    ALL: Operation.DropOp.ValueType  # 1
    DATA: Operation.DropOp.ValueType  # 2
    ATTR: Operation.DropOp.ValueType  # 3
    TYPE: Operation.DropOp.ValueType  # 4

    SCHEMA_FIELD_NUMBER: _builtins.int
    DROP_ATTR_FIELD_NUMBER: _builtins.int
    DROP_ALL_FIELD_NUMBER: _builtins.int
    DROP_OP_FIELD_NUMBER: _builtins.int
    DROP_VALUE_FIELD_NUMBER: _builtins.int
    RUN_IN_BACKGROUND_FIELD_NUMBER: _builtins.int
    schema: _builtins.str
    drop_attr: _builtins.str
    drop_all: _builtins.bool
    drop_op: Global___Operation.DropOp.ValueType
    drop_value: _builtins.str
    """If drop_op is ATTR or TYPE, drop_value holds the name of the predicate or
    type to delete.
    """
    run_in_background: _builtins.bool
    """run indexes in background."""
    def __init__(
        self,
        *,
        schema: _builtins.str = ...,
        drop_attr: _builtins.str = ...,
        drop_all: _builtins.bool = ...,
        drop_op: Global___Operation.DropOp.ValueType = ...,
        drop_value: _builtins.str = ...,
        run_in_background: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["drop_all", b"drop_all", "drop_attr", b"drop_attr", "drop_op", b"drop_op", "drop_value", b"drop_value", "run_in_background", b"run_in_background", "schema", b"schema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Operation: _TypeAlias = Operation  # noqa: Y015

@_typing.final
class Payload(_message.Message):
    """Worker services."""

    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    Data: _builtins.bytes
    def __init__(
        self,
        *,
        Data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["Data", b"Data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Payload: _TypeAlias = Payload  # noqa: Y015

@_typing.final
class TxnContext(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    START_TS_FIELD_NUMBER: _builtins.int
    COMMIT_TS_FIELD_NUMBER: _builtins.int
    ABORTED_FIELD_NUMBER: _builtins.int
    KEYS_FIELD_NUMBER: _builtins.int
    PREDS_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    start_ts: _builtins.int
    commit_ts: _builtins.int
    aborted: _builtins.bool
    hash: _builtins.str
    @_builtins.property
    def keys(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """List of keys to be used for conflict detection."""

    @_builtins.property
    def preds(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """List of predicates involved in this transaction."""

    def __init__(
        self,
        *,
        start_ts: _builtins.int = ...,
        commit_ts: _builtins.int = ...,
        aborted: _builtins.bool = ...,
        keys: _abc.Iterable[_builtins.str] | None = ...,
        preds: _abc.Iterable[_builtins.str] | None = ...,
        hash: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aborted", b"aborted", "commit_ts", b"commit_ts", "hash", b"hash", "keys", b"keys", "preds", b"preds", "start_ts", b"start_ts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TxnContext: _TypeAlias = TxnContext  # noqa: Y015

@_typing.final
class Check(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Check: _TypeAlias = Check  # noqa: Y015

@_typing.final
class Version(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Version: _TypeAlias = Version  # noqa: Y015

@_typing.final
class Latency(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARSING_NS_FIELD_NUMBER: _builtins.int
    PROCESSING_NS_FIELD_NUMBER: _builtins.int
    ENCODING_NS_FIELD_NUMBER: _builtins.int
    ASSIGN_TIMESTAMP_NS_FIELD_NUMBER: _builtins.int
    TOTAL_NS_FIELD_NUMBER: _builtins.int
    parsing_ns: _builtins.int
    processing_ns: _builtins.int
    encoding_ns: _builtins.int
    assign_timestamp_ns: _builtins.int
    total_ns: _builtins.int
    def __init__(
        self,
        *,
        parsing_ns: _builtins.int = ...,
        processing_ns: _builtins.int = ...,
        encoding_ns: _builtins.int = ...,
        assign_timestamp_ns: _builtins.int = ...,
        total_ns: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["assign_timestamp_ns", b"assign_timestamp_ns", "encoding_ns", b"encoding_ns", "parsing_ns", b"parsing_ns", "processing_ns", b"processing_ns", "total_ns", b"total_ns"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Latency: _TypeAlias = Latency  # noqa: Y015

@_typing.final
class Metrics(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class NumUidsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NUM_UIDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def num_uids(self) -> _containers.ScalarMap[_builtins.str, _builtins.int]:
        """num_uids is the map of number of uids processed by each attribute."""

    def __init__(
        self,
        *,
        num_uids: _abc.Mapping[_builtins.str, _builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["num_uids", b"num_uids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Metrics: _TypeAlias = Metrics  # noqa: Y015

@_typing.final
class NQuad(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBJECT_FIELD_NUMBER: _builtins.int
    PREDICATE_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    OBJECT_VALUE_FIELD_NUMBER: _builtins.int
    LANG_FIELD_NUMBER: _builtins.int
    FACETS_FIELD_NUMBER: _builtins.int
    NAMESPACE_FIELD_NUMBER: _builtins.int
    subject: _builtins.str
    predicate: _builtins.str
    object_id: _builtins.str
    lang: _builtins.str
    namespace: _builtins.int
    @_builtins.property
    def object_value(self) -> Global___Value: ...
    @_builtins.property
    def facets(self) -> _containers.RepeatedCompositeFieldContainer[Global___Facet]: ...
    def __init__(
        self,
        *,
        subject: _builtins.str = ...,
        predicate: _builtins.str = ...,
        object_id: _builtins.str = ...,
        object_value: Global___Value | None = ...,
        lang: _builtins.str = ...,
        facets: _abc.Iterable[Global___Facet] | None = ...,
        namespace: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["object_value", b"object_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["facets", b"facets", "lang", b"lang", "namespace", b"namespace", "object_id", b"object_id", "object_value", b"object_value", "predicate", b"predicate", "subject", b"subject"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NQuad: _TypeAlias = NQuad  # noqa: Y015

@_typing.final
class Value(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEFAULT_VAL_FIELD_NUMBER: _builtins.int
    BYTES_VAL_FIELD_NUMBER: _builtins.int
    INT_VAL_FIELD_NUMBER: _builtins.int
    BOOL_VAL_FIELD_NUMBER: _builtins.int
    STR_VAL_FIELD_NUMBER: _builtins.int
    DOUBLE_VAL_FIELD_NUMBER: _builtins.int
    GEO_VAL_FIELD_NUMBER: _builtins.int
    DATE_VAL_FIELD_NUMBER: _builtins.int
    DATETIME_VAL_FIELD_NUMBER: _builtins.int
    PASSWORD_VAL_FIELD_NUMBER: _builtins.int
    UID_VAL_FIELD_NUMBER: _builtins.int
    BIGFLOAT_VAL_FIELD_NUMBER: _builtins.int
    VFLOAT32_VAL_FIELD_NUMBER: _builtins.int
    default_val: _builtins.str
    bytes_val: _builtins.bytes
    int_val: _builtins.int
    bool_val: _builtins.bool
    str_val: _builtins.str
    double_val: _builtins.float
    geo_val: _builtins.bytes
    """Geo data in WKB format"""
    date_val: _builtins.bytes
    datetime_val: _builtins.bytes
    password_val: _builtins.str
    uid_val: _builtins.int
    bigfloat_val: _builtins.bytes
    vfloat32_val: _builtins.bytes
    def __init__(
        self,
        *,
        default_val: _builtins.str = ...,
        bytes_val: _builtins.bytes = ...,
        int_val: _builtins.int = ...,
        bool_val: _builtins.bool = ...,
        str_val: _builtins.str = ...,
        double_val: _builtins.float = ...,
        geo_val: _builtins.bytes = ...,
        date_val: _builtins.bytes = ...,
        datetime_val: _builtins.bytes = ...,
        password_val: _builtins.str = ...,
        uid_val: _builtins.int = ...,
        bigfloat_val: _builtins.bytes = ...,
        vfloat32_val: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bigfloat_val", b"bigfloat_val", "bool_val", b"bool_val", "bytes_val", b"bytes_val", "date_val", b"date_val", "datetime_val", b"datetime_val", "default_val", b"default_val", "double_val", b"double_val", "geo_val", b"geo_val", "int_val", b"int_val", "password_val", b"password_val", "str_val", b"str_val", "uid_val", b"uid_val", "val", b"val", "vfloat32_val", b"vfloat32_val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bigfloat_val", b"bigfloat_val", "bool_val", b"bool_val", "bytes_val", b"bytes_val", "date_val", b"date_val", "datetime_val", b"datetime_val", "default_val", b"default_val", "double_val", b"double_val", "geo_val", b"geo_val", "int_val", b"int_val", "password_val", b"password_val", "str_val", b"str_val", "uid_val", b"uid_val", "val", b"val", "vfloat32_val", b"vfloat32_val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_val: _TypeAlias = _typing.Literal["default_val", "bytes_val", "int_val", "bool_val", "str_val", "double_val", "geo_val", "date_val", "datetime_val", "password_val", "uid_val", "bigfloat_val", "vfloat32_val"]  # noqa: Y015
    _WhichOneofArgType_val: _TypeAlias = _typing.Literal["val", b"val"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_val) -> _WhichOneofReturnType_val | None: ...

Global___Value: _TypeAlias = Value  # noqa: Y015

@_typing.final
class Facet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ValType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ValTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Facet._ValType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STRING: Facet._ValType.ValueType  # 0
        INT: Facet._ValType.ValueType  # 1
        FLOAT: Facet._ValType.ValueType  # 2
        BOOL: Facet._ValType.ValueType  # 3
        DATETIME: Facet._ValType.ValueType  # 4

    class ValType(_ValType, metaclass=_ValTypeEnumTypeWrapper): ...
    STRING: Facet.ValType.ValueType  # 0
    INT: Facet.ValType.ValueType  # 1
    FLOAT: Facet.ValType.ValueType  # 2
    BOOL: Facet.ValType.ValueType  # 3
    DATETIME: Facet.ValType.ValueType  # 4

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    VAL_TYPE_FIELD_NUMBER: _builtins.int
    TOKENS_FIELD_NUMBER: _builtins.int
    ALIAS_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.bytes
    val_type: Global___Facet.ValType.ValueType
    alias: _builtins.str
    """not stored, only used for query."""
    @_builtins.property
    def tokens(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """tokens of value."""

    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
        val_type: Global___Facet.ValType.ValueType = ...,
        tokens: _abc.Iterable[_builtins.str] | None = ...,
        alias: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alias", b"alias", "key", b"key", "tokens", b"tokens", "val_type", b"val_type", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Facet: _TypeAlias = Facet  # noqa: Y015

@_typing.final
class LoginRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERID_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: _builtins.int
    NAMESPACE_FIELD_NUMBER: _builtins.int
    userid: _builtins.str
    password: _builtins.str
    refresh_token: _builtins.str
    namespace: _builtins.int
    def __init__(
        self,
        *,
        userid: _builtins.str = ...,
        password: _builtins.str = ...,
        refresh_token: _builtins.str = ...,
        namespace: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["namespace", b"namespace", "password", b"password", "refresh_token", b"refresh_token", "userid", b"userid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoginRequest: _TypeAlias = LoginRequest  # noqa: Y015

@_typing.final
class Jwt(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACCESS_JWT_FIELD_NUMBER: _builtins.int
    REFRESH_JWT_FIELD_NUMBER: _builtins.int
    access_jwt: _builtins.str
    refresh_jwt: _builtins.str
    def __init__(
        self,
        *,
        access_jwt: _builtins.str = ...,
        refresh_jwt: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_jwt", b"access_jwt", "refresh_jwt", b"refresh_jwt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Jwt: _TypeAlias = Jwt  # noqa: Y015

@_typing.final
class RunDQLRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class VarsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    DQL_QUERY_FIELD_NUMBER: _builtins.int
    VARS_FIELD_NUMBER: _builtins.int
    READ_ONLY_FIELD_NUMBER: _builtins.int
    BEST_EFFORT_FIELD_NUMBER: _builtins.int
    RESP_FORMAT_FIELD_NUMBER: _builtins.int
    dql_query: _builtins.str
    read_only: _builtins.bool
    best_effort: _builtins.bool
    resp_format: Global___Request.RespFormat.ValueType
    @_builtins.property
    def vars(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        dql_query: _builtins.str = ...,
        vars: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        read_only: _builtins.bool = ...,
        best_effort: _builtins.bool = ...,
        resp_format: Global___Request.RespFormat.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["best_effort", b"best_effort", "dql_query", b"dql_query", "read_only", b"read_only", "resp_format", b"resp_format", "vars", b"vars"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RunDQLRequest: _TypeAlias = RunDQLRequest  # noqa: Y015

@_typing.final
class AllocateIDsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HOW_MANY_FIELD_NUMBER: _builtins.int
    LEASE_TYPE_FIELD_NUMBER: _builtins.int
    how_many: _builtins.int
    lease_type: Global___LeaseType.ValueType
    def __init__(
        self,
        *,
        how_many: _builtins.int = ...,
        lease_type: Global___LeaseType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["how_many", b"how_many", "lease_type", b"lease_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AllocateIDsRequest: _TypeAlias = AllocateIDsRequest  # noqa: Y015

@_typing.final
class AllocateIDsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    START_FIELD_NUMBER: _builtins.int
    END_FIELD_NUMBER: _builtins.int
    start: _builtins.int
    end: _builtins.int
    """inclusive"""
    def __init__(
        self,
        *,
        start: _builtins.int = ...,
        end: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end", b"end", "start", b"start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AllocateIDsResponse: _TypeAlias = AllocateIDsResponse  # noqa: Y015

@_typing.final
class CreateNamespaceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CreateNamespaceRequest: _TypeAlias = CreateNamespaceRequest  # noqa: Y015

@_typing.final
class CreateNamespaceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: _builtins.int
    namespace: _builtins.int
    def __init__(
        self,
        *,
        namespace: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["namespace", b"namespace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateNamespaceResponse: _TypeAlias = CreateNamespaceResponse  # noqa: Y015

@_typing.final
class DropNamespaceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: _builtins.int
    namespace: _builtins.int
    def __init__(
        self,
        *,
        namespace: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["namespace", b"namespace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DropNamespaceRequest: _TypeAlias = DropNamespaceRequest  # noqa: Y015

@_typing.final
class DropNamespaceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DropNamespaceResponse: _TypeAlias = DropNamespaceResponse  # noqa: Y015

@_typing.final
class ListNamespacesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ListNamespacesRequest: _TypeAlias = ListNamespacesRequest  # noqa: Y015

@_typing.final
class ListNamespacesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class NamespacesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___Namespace: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___Namespace | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NAMESPACES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def namespaces(self) -> _containers.MessageMap[_builtins.int, Global___Namespace]: ...
    def __init__(
        self,
        *,
        namespaces: _abc.Mapping[_builtins.int, Global___Namespace] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["namespaces", b"namespaces"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListNamespacesResponse: _TypeAlias = ListNamespacesResponse  # noqa: Y015

@_typing.final
class Namespace(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Namespace: _TypeAlias = Namespace  # noqa: Y015

@_typing.final
class UpdateExtSnapshotStreamingStateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    START_FIELD_NUMBER: _builtins.int
    FINISH_FIELD_NUMBER: _builtins.int
    DROP_DATA_FIELD_NUMBER: _builtins.int
    start: _builtins.bool
    finish: _builtins.bool
    drop_data: _builtins.bool
    def __init__(
        self,
        *,
        start: _builtins.bool = ...,
        finish: _builtins.bool = ...,
        drop_data: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["drop_data", b"drop_data", "finish", b"finish", "start", b"start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateExtSnapshotStreamingStateRequest: _TypeAlias = UpdateExtSnapshotStreamingStateRequest  # noqa: Y015

@_typing.final
class UpdateExtSnapshotStreamingStateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GROUPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def groups(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        groups: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["groups", b"groups"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateExtSnapshotStreamingStateResponse: _TypeAlias = UpdateExtSnapshotStreamingStateResponse  # noqa: Y015

@_typing.final
class StreamExtSnapshotRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GROUP_ID_FIELD_NUMBER: _builtins.int
    FORWARD_FIELD_NUMBER: _builtins.int
    PKT_FIELD_NUMBER: _builtins.int
    group_id: _builtins.int
    forward: _builtins.bool
    @_builtins.property
    def pkt(self) -> Global___StreamPacket: ...
    def __init__(
        self,
        *,
        group_id: _builtins.int = ...,
        forward: _builtins.bool = ...,
        pkt: Global___StreamPacket | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pkt", b"pkt"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["forward", b"forward", "group_id", b"group_id", "pkt", b"pkt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamExtSnapshotRequest: _TypeAlias = StreamExtSnapshotRequest  # noqa: Y015

@_typing.final
class StreamExtSnapshotResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StreamExtSnapshotResponse: _TypeAlias = StreamExtSnapshotResponse  # noqa: Y015

@_typing.final
class StreamPacket(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    DONE_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    done: _builtins.bool
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        done: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "done", b"done"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamPacket: _TypeAlias = StreamPacket  # noqa: Y015
